# a docker-compose file with a postgres 14 service

version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - 5432:5432
    volumes:
    - ./data:/var/lib/postgresql/data
