# Generated by Django 4.2.6 on 2023-10-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protein_Group', models.TextField(blank=True, null=True)),
                ('Protein_Ids', models.TextField(blank=True, null=True)),
                ('Protein_Names', models.TextField(blank=True, null=True)),
                ('Genes', models.TextField(blank=True, null=True)),
                ('Proteotypic', models.IntegerField(blank=True, null=True)),
                ('Stripped_Sequence', models.TextField(blank=True, null=True)),
                ('Modified_Sequence', models.TextField(blank=True, null=True)),
                ('Precursor_Id', models.TextField(blank=True, null=True)),
                ('n_Samples', models.IntegerField(blank=True, null=True)),
                ('n_TimePoints', models.IntegerField(blank=True, null=True)),
                ('tau_POI', models.FloatField(blank=True, null=True)),
                ('tau_POI_lower_bound', models.FloatField(blank=True, null=True)),
                ('tau_POI_upper_bound', models.FloatField(blank=True, null=True)),
                ('tau_POI_range', models.FloatField(blank=True, null=True)),
                ('tau_POI_range_relative', models.FloatField(blank=True, null=True)),
                ('HalfLife_POI', models.FloatField(blank=True, null=True)),
                ('HalfLife_POI_lower_bound', models.FloatField(blank=True, null=True)),
                ('HalfLife_POI_upper_bound', models.FloatField(blank=True, null=True)),
                ('HalfLife_POI_range', models.FloatField(blank=True, null=True)),
                ('HalfLife_POI_range_relative', models.FloatField(blank=True, null=True)),
                ('rss', models.FloatField(blank=True, null=True)),
                ('rs', models.JSONField(blank=True, null=True)),
                ('AverageRSS', models.FloatField(blank=True, null=True)),
                ('Engine', models.TextField(blank=True, null=True)),
                ('Tissue', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TurnoverDataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sample_Name', models.TextField(blank=True, null=True)),
                ('SampleL', models.FloatField(blank=True, null=True)),
                ('SampleH', models.FloatField(blank=True, null=True)),
                ('Sample_H_over_HL', models.FloatField(blank=True, null=True)),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='turnover_atlas.turnoverdata')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
