# Generated by Django 4.2.6 on 2023-10-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionIDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protein_Group', models.TextField(blank=True, null=True)),
                ('Genes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
