# Generated by Django 4.2.6 on 2023-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0002_accessionidmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGroupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sample_Name', models.TextField(blank=True, null=True)),
                ('Sample_Label', models.TextField(blank=True, null=True)),
                ('Days', models.IntegerField(blank=True, null=True)),
                ('Replicate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
