# Generated by Django 4.2.6 on 2023-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0003_samplegroupmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('r', models.FloatField()),
                ('n', models.FloatField()),
                ('eps', models.FloatField()),
                ('min', models.FloatField()),
                ('Engine', models.TextField()),
                ('Tissue', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
