# Generated by Django 4.2.6 on 2023-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0004_modelparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelparameters',
            name='k_pool',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnoverdata',
            name='tau_model',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
