# Generated by Django 4.2.6 on 2023-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0006_alter_turnoverdata_protein_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoverdata',
            name='Genes',
            field=models.TextField(db_index=True, default=''),
            preserve_default=False,
        ),
    ]
