# Generated by Django 4.2.6 on 2023-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0007_alter_turnoverdata_genes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessionID', models.TextField(db_index=True)),
                ('Sequence', models.TextField()),
            ],
            options={
                'ordering': ['AccessionID'],
            },
        ),
    ]
