# Generated by Django 4.2.6 on 2023-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
