# Generated by Django 4.2.6 on 2023-11-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnover_atlas', '0010_session_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='file',
            new_name='details',
        ),
    ]
